server:
  port: 9005

spring:
  application:
    name: pharmacy-service
  config:
    import: optional:nacos:${spring.application.name}.yml
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace:
      config:
        file-extension: yml

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
